#!/bin/bash
printf "5i %s 4i %s + 8o p\n" "$(tr 'water' '01234' <<< "$WATER")" "$(tr 'stir' '0123' <<< "$STIR")" | dc | cut -d. -f1 | { result=$(head -n1); printf "8o %s p\n" "$result"; } | dc | tr '01234567' 'bestchol'
